// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: qjG0g-Rmz0BeDH
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicCardHeaderTitlePrimary.module.css"; // plasmic-import: qjG0g-Rmz0BeDH/css

export type PlasmicCardHeaderTitlePrimary__VariantMembers = {};

export type PlasmicCardHeaderTitlePrimary__VariantsArgs = {};
type VariantPropType = keyof PlasmicCardHeaderTitlePrimary__VariantsArgs;
export const PlasmicCardHeaderTitlePrimary__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCardHeaderTitlePrimary__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicCardHeaderTitlePrimary__ArgsType;
export const PlasmicCardHeaderTitlePrimary__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicCardHeaderTitlePrimary__OverridesType = {
  root?: p.Flex<"hgroup">;
  headlineLabel?: p.Flex<"h5">;
  subhead?: p.Flex<"div">;
};

export interface DefaultCardHeaderTitlePrimaryProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  className?: string;
}

function PlasmicCardHeaderTitlePrimary__RenderFunc(props: {
  variants: PlasmicCardHeaderTitlePrimary__VariantsArgs;
  args: PlasmicCardHeaderTitlePrimary__ArgsType;
  overrides: PlasmicCardHeaderTitlePrimary__OverridesType;
  dataFetches?: PlasmicCardHeaderTitlePrimary__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"hgroup"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <h5
        data-plasmic-name={"headlineLabel"}
        data-plasmic-override={overrides.headlineLabel}
        className={classNames(defaultcss.h5, sty.headlineLabel)}
      >
        <div className={classNames(defaultcss.all, sty.freeBox___6LsQk)}>
          {p.renderPlasmicSlot({
            defaultContents: "Headline Title",
            value: args.children,
            className: classNames(sty.slotChildren)
          })}
        </div>
      </h5>

      <div
        data-plasmic-name={"subhead"}
        data-plasmic-override={overrides.subhead}
        className={classNames(defaultcss.all, sty.subhead)}
      >
        <div className={classNames(defaultcss.all, sty.freeBox__vAf1P)}>
          {p.renderPlasmicSlot({
            defaultContents: "Subhead",
            value: args.slot,
            className: classNames(sty.slotSlot)
          })}
        </div>
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "headlineLabel", "subhead"],
  headlineLabel: ["headlineLabel"],
  subhead: ["subhead"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "hgroup";
  headlineLabel: "h5";
  subhead: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCardHeaderTitlePrimary__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCardHeaderTitlePrimary__VariantsArgs;
    args?: PlasmicCardHeaderTitlePrimary__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicCardHeaderTitlePrimary__Fetches;
  } & Omit<PlasmicCardHeaderTitlePrimary__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCardHeaderTitlePrimary__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCardHeaderTitlePrimary__ArgProps,
      internalVariantPropNames: PlasmicCardHeaderTitlePrimary__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicCardHeaderTitlePrimary__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCardHeaderTitlePrimary";
  } else {
    func.displayName = `PlasmicCardHeaderTitlePrimary.${nodeName}`;
  }
  return func;
}

export const PlasmicCardHeaderTitlePrimary = Object.assign(
  // Top-level PlasmicCardHeaderTitlePrimary renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    headlineLabel: makeNodeComponent("headlineLabel"),
    subhead: makeNodeComponent("subhead"),

    // Metadata about props expected for PlasmicCardHeaderTitlePrimary
    internalVariantProps: PlasmicCardHeaderTitlePrimary__VariantProps,
    internalArgProps: PlasmicCardHeaderTitlePrimary__ArgProps
  }
);

export default PlasmicCardHeaderTitlePrimary;
/* prettier-ignore-end */
