// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: yR30m43Hlvxo_B
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import IconStripeLogo from "../../IconStripeLogo"; // plasmic-import: 9qvamr3j2pv4L-/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicButtonStripeVerification.module.css"; // plasmic-import: yR30m43Hlvxo_B/css

import IdVerificationIcon from "./icons/PlasmicIcon__IdVerification"; // plasmic-import: nK_Y1D8eBETxbHk/icon

export type PlasmicButtonStripeVerification__VariantMembers = {
  icon: "icon";
  logo: "logo";
  size: "_180" | "_270" | "_360";
};

export type PlasmicButtonStripeVerification__VariantsArgs = {
  icon?: SingleBooleanChoiceArg<"icon">;
  logo?: SingleBooleanChoiceArg<"logo">;
  size?: SingleChoiceArg<"_180" | "_270" | "_360">;
};

type VariantPropType = keyof PlasmicButtonStripeVerification__VariantsArgs;
export const PlasmicButtonStripeVerification__VariantProps =
  new Array<VariantPropType>("icon", "logo", "size");

export type PlasmicButtonStripeVerification__ArgsType = {
  text?: React.ReactNode;
  id?: string;
};

type ArgPropType = keyof PlasmicButtonStripeVerification__ArgsType;
export const PlasmicButtonStripeVerification__ArgProps = new Array<ArgPropType>(
  "text",
  "id"
);

export type PlasmicButtonStripeVerification__OverridesType = {
  root?: p.Flex<"button">;
  freeBox?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  textParent?: p.Flex<"div">;
  textBg?: p.Flex<"div">;
  iconStripeLogo?: p.Flex<typeof IconStripeLogo>;
};

export interface DefaultButtonStripeVerificationProps {
  text?: React.ReactNode;
  id?: string;
  icon?: SingleBooleanChoiceArg<"icon">;
  logo?: SingleBooleanChoiceArg<"logo">;
  size?: SingleChoiceArg<"_180" | "_270" | "_360">;
  className?: string;
}

function PlasmicButtonStripeVerification__RenderFunc(props: {
  variants: PlasmicButtonStripeVerification__VariantsArgs;
  args: PlasmicButtonStripeVerification__ArgsType;
  overrides: PlasmicButtonStripeVerification__OverridesType;
  dataFetches?: PlasmicButtonStripeVerification__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const [isRootHover, triggerRootHoverProps] = useTrigger("useHover", {});
  const triggers = {
    hover_root: isRootHover
  };

  return (
    <p.Stack
      as={"button"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        defaultcss.button,
        projectcss.root_reset,
        sty.root,
        "VerifyButton" as const,
        {
          [sty.root__size__180]: hasVariant(variants, "size", "_180"),
          [sty.root__size__270]: hasVariant(variants, "size", "_270"),
          [sty.root__size__360]: hasVariant(variants, "size", "_360")
        }
      )}
      id={args.id}
      data-plasmic-trigger-props={[triggerRootHoverProps]}
    >
      {(hasVariant(variants, "icon", "icon") ? false : true) ? (
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(defaultcss.all, sty.freeBox, {
            [sty.freeBox__icon]: hasVariant(variants, "icon", "icon"),
            [sty.freeBox__size__180]: hasVariant(variants, "size", "_180")
          })}
        >
          <IdVerificationIcon
            data-plasmic-name={"svg"}
            data-plasmic-override={overrides.svg}
            className={classNames(defaultcss.all, sty.svg, {
              [sty.svg__icon]: hasVariant(variants, "icon", "icon"),
              [sty.svg__size__180]: hasVariant(variants, "size", "_180")
            })}
            role={"img"}
          />
        </div>
      ) : null}

      <div
        data-plasmic-name={"textParent"}
        data-plasmic-override={overrides.textParent}
        className={classNames(defaultcss.all, sty.textParent, {
          [sty.textParent__logo]: hasVariant(variants, "logo", "logo"),
          [sty.textParent__size__180]: hasVariant(variants, "size", "_180")
        })}
      >
        <div
          data-plasmic-name={"textBg"}
          data-plasmic-override={overrides.textBg}
          className={classNames(defaultcss.all, sty.textBg)}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Get verified with",
            value: args.text,
            className: classNames(sty.slotText, {
              [sty.slotText__logo]: hasVariant(variants, "logo", "logo"),
              [sty.slotText__size__180]: hasVariant(variants, "size", "_180")
            })
          })}
        </div>
      </div>

      {(hasVariant(variants, "logo", "logo") ? false : true) ? (
        <IconStripeLogo
          data-plasmic-name={"iconStripeLogo"}
          data-plasmic-override={overrides.iconStripeLogo}
          className={classNames("__wab_instance", sty.iconStripeLogo, {
            [sty.iconStripeLogo__logo]: hasVariant(variants, "logo", "logo"),
            [sty.iconStripeLogo__size__180]: hasVariant(
              variants,
              "size",
              "_180"
            )
          })}
          color={triggers.hover_root ? ("white" as const) : ("burple" as const)}
          size={
            hasVariant(variants, "size", "_180")
              ? ("_18" as const)
              : ("_48" as const)
          }
        />
      ) : null}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "svg", "textParent", "textBg", "iconStripeLogo"],
  freeBox: ["freeBox", "svg"],
  svg: ["svg"],
  textParent: ["textParent", "textBg"],
  textBg: ["textBg"],
  iconStripeLogo: ["iconStripeLogo"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "button";
  freeBox: "div";
  svg: "svg";
  textParent: "div";
  textBg: "div";
  iconStripeLogo: typeof IconStripeLogo;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonStripeVerification__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonStripeVerification__VariantsArgs;
    args?: PlasmicButtonStripeVerification__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicButtonStripeVerification__Fetches;
  } & Omit<PlasmicButtonStripeVerification__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicButtonStripeVerification__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicButtonStripeVerification__ArgProps,
      internalVariantPropNames: PlasmicButtonStripeVerification__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicButtonStripeVerification__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButtonStripeVerification";
  } else {
    func.displayName = `PlasmicButtonStripeVerification.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonStripeVerification = Object.assign(
  // Top-level PlasmicButtonStripeVerification renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    svg: makeNodeComponent("svg"),
    textParent: makeNodeComponent("textParent"),
    textBg: makeNodeComponent("textBg"),
    iconStripeLogo: makeNodeComponent("iconStripeLogo"),

    // Metadata about props expected for PlasmicButtonStripeVerification
    internalVariantProps: PlasmicButtonStripeVerification__VariantProps,
    internalArgProps: PlasmicButtonStripeVerification__ArgProps
  }
);

export default PlasmicButtonStripeVerification;
/* prettier-ignore-end */
