// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: 1y8tRQlAIZcidK
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicServiceProcessCard.module.css"; // plasmic-import: 1y8tRQlAIZcidK/css

export type PlasmicServiceProcessCard__VariantMembers = {
  size: "_360";
};

export type PlasmicServiceProcessCard__VariantsArgs = {
  size?: SingleChoiceArg<"_360">;
};

type VariantPropType = keyof PlasmicServiceProcessCard__VariantsArgs;
export const PlasmicServiceProcessCard__VariantProps =
  new Array<VariantPropType>("size");

export type PlasmicServiceProcessCard__ArgsType = {
  children?: React.ReactNode;
  slot?: React.ReactNode;
};

type ArgPropType = keyof PlasmicServiceProcessCard__ArgsType;
export const PlasmicServiceProcessCard__ArgProps = new Array<ArgPropType>(
  "children",
  "slot"
);

export type PlasmicServiceProcessCard__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultServiceProcessCardProps {
  children?: React.ReactNode;
  slot?: React.ReactNode;
  size?: SingleChoiceArg<"_360">;
  className?: string;
}

function PlasmicServiceProcessCard__RenderFunc(props: {
  variants: PlasmicServiceProcessCard__VariantsArgs;
  args: PlasmicServiceProcessCard__ArgsType;
  overrides: PlasmicServiceProcessCard__OverridesType;
  dataFetches?: PlasmicServiceProcessCard__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__size__360]: hasVariant(variants, "size", "_360")
      })}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox___7XUvV, {
          [sty.freeBox__size__360___7XUvVdc13D]: hasVariant(
            variants,
            "size",
            "_360"
          )
        })}
      >
        <div
          className={classNames(defaultcss.all, sty.freeBox__m3QSf, {
            [sty.freeBox__size__360__m3QSfdc13D]: hasVariant(
              variants,
              "size",
              "_360"
            )
          })}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Headline Title",
            value: args.slot,
            className: classNames(sty.slotSlot, {
              [sty.slotSlot__size__360]: hasVariant(variants, "size", "_360")
            })
          })}
        </div>

        {p.renderPlasmicSlot({
          defaultContents: hasVariant(variants, "size", "_360")
            ? "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commo"
            : "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commo",
          value: args.children,
          className: classNames(sty.slotChildren, {
            [sty.slotChildren__size__360]: hasVariant(variants, "size", "_360")
          })
        })}
      </p.Stack>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicServiceProcessCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicServiceProcessCard__VariantsArgs;
    args?: PlasmicServiceProcessCard__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicServiceProcessCard__Fetches;
  } & Omit<PlasmicServiceProcessCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicServiceProcessCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicServiceProcessCard__ArgProps,
      internalVariantPropNames: PlasmicServiceProcessCard__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicServiceProcessCard__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicServiceProcessCard";
  } else {
    func.displayName = `PlasmicServiceProcessCard.${nodeName}`;
  }
  return func;
}

export const PlasmicServiceProcessCard = Object.assign(
  // Top-level PlasmicServiceProcessCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicServiceProcessCard
    internalVariantProps: PlasmicServiceProcessCard__VariantProps,
    internalArgProps: PlasmicServiceProcessCard__ArgProps
  }
);

export default PlasmicServiceProcessCard;
/* prettier-ignore-end */
