// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: DT3IZo3T2FBSUKV
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import MenuIconListItem from "../../MenuIconListItem"; // plasmic-import: A4cpU1IW2YGn9yX/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicPanelMemberSectionAccount.module.css"; // plasmic-import: DT3IZo3T2FBSUKV/css

import NotificationIcon from "./icons/PlasmicIcon__Notification"; // plasmic-import: 5BbJfo5oWzkNJl9/icon
import SettingsIcon from "./icons/PlasmicIcon__Settings"; // plasmic-import: qXuMbcpLVB2M0qL/icon

export type PlasmicPanelMemberSectionAccount__VariantMembers = {};

export type PlasmicPanelMemberSectionAccount__VariantsArgs = {};
type VariantPropType = keyof PlasmicPanelMemberSectionAccount__VariantsArgs;
export const PlasmicPanelMemberSectionAccount__VariantProps =
  new Array<VariantPropType>();

export type PlasmicPanelMemberSectionAccount__ArgsType = {};
type ArgPropType = keyof PlasmicPanelMemberSectionAccount__ArgsType;
export const PlasmicPanelMemberSectionAccount__ArgProps =
  new Array<ArgPropType>();

export type PlasmicPanelMemberSectionAccount__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultPanelMemberSectionAccountProps {
  className?: string;
}

function PlasmicPanelMemberSectionAccount__RenderFunc(props: {
  variants: PlasmicPanelMemberSectionAccount__VariantsArgs;
  args: PlasmicPanelMemberSectionAccount__ArgsType;
  overrides: PlasmicPanelMemberSectionAccount__OverridesType;
  dataFetches?: PlasmicPanelMemberSectionAccount__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        hasGap={true}
        className={classNames(defaultcss.all, sty.freeBox__hmsk5)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__swAj
          )}
        >
          {"Account"}
        </div>
      </p.Stack>

      <MenuIconListItem
        className={classNames("__wab_instance", sty.menuIconListItem__whUu)}
        navIcon={
          <div className={classNames(defaultcss.all, sty.freeBox__g8ZCe)}>
            <NotificationIcon
              className={classNames(defaultcss.all, sty.svg__pq7HQ)}
              role={"img"}
            />
          </div>
        }
        navText={"Notifications"}
      />

      <MenuIconListItem
        className={classNames("__wab_instance", sty.menuIconListItem__k9LoD)}
        navIcon={
          <div className={classNames(defaultcss.all, sty.freeBox__ruRgh)}>
            <SettingsIcon
              className={classNames(defaultcss.all, sty.svg__fXsKn)}
              role={"img"}
            />
          </div>
        }
        navText={"Settings"}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPanelMemberSectionAccount__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPanelMemberSectionAccount__VariantsArgs;
    args?: PlasmicPanelMemberSectionAccount__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicPanelMemberSectionAccount__Fetches;
  } & Omit<PlasmicPanelMemberSectionAccount__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPanelMemberSectionAccount__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPanelMemberSectionAccount__ArgProps,
      internalVariantPropNames: PlasmicPanelMemberSectionAccount__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicPanelMemberSectionAccount__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPanelMemberSectionAccount";
  } else {
    func.displayName = `PlasmicPanelMemberSectionAccount.${nodeName}`;
  }
  return func;
}

export const PlasmicPanelMemberSectionAccount = Object.assign(
  // Top-level PlasmicPanelMemberSectionAccount renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicPanelMemberSectionAccount
    internalVariantProps: PlasmicPanelMemberSectionAccount__VariantProps,
    internalArgProps: PlasmicPanelMemberSectionAccount__ArgProps
  }
);

export default PlasmicPanelMemberSectionAccount;
/* prettier-ignore-end */
