// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: jLNe8Bxz-b4Dne
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ButtonCircleDelete from "../../ButtonCircleDelete"; // plasmic-import: ADEYruGVISG4-wd/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicTableBillingRecord.module.css"; // plasmic-import: jLNe8Bxz-b4Dne/css

import CircleCheckedIcon from "./icons/PlasmicIcon__CircleChecked"; // plasmic-import: Rx_TV1hYzOOAuX3/icon

export type PlasmicTableBillingRecord__VariantMembers = {};

export type PlasmicTableBillingRecord__VariantsArgs = {};
type VariantPropType = keyof PlasmicTableBillingRecord__VariantsArgs;
export const PlasmicTableBillingRecord__VariantProps =
  new Array<VariantPropType>();

export type PlasmicTableBillingRecord__ArgsType = {};
type ArgPropType = keyof PlasmicTableBillingRecord__ArgsType;
export const PlasmicTableBillingRecord__ArgProps = new Array<ArgPropType>();

export type PlasmicTableBillingRecord__OverridesType = {
  root?: p.Flex<"div">;
  svg?: p.Flex<"svg">;
  buttonCircleDelete?: p.Flex<typeof ButtonCircleDelete>;
};

export interface DefaultTableBillingRecordProps {
  className?: string;
}

function PlasmicTableBillingRecord__RenderFunc(props: {
  variants: PlasmicTableBillingRecord__VariantsArgs;
  args: PlasmicTableBillingRecord__ArgsType;
  overrides: PlasmicTableBillingRecord__OverridesType;
  dataFetches?: PlasmicTableBillingRecord__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div className={classNames(defaultcss.all, sty.freeBox___8Uy3S)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__zscxh
          )}
        >
          {"Card brand"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__uErFh)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__mHFp
          )}
        >
          {"Type"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox___7GpGo)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__k1PkD
          )}
        >
          {"XXXX"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__db2Ej)}>
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__jtHbx
          )}
        >
          {"XX"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__mfyRi
          )}
        >
          {"/"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__gX0Ax
          )}
        >
          {"XXXX"}
        </div>
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__tZoUr)}>
        <CircleCheckedIcon
          data-plasmic-name={"svg"}
          data-plasmic-override={overrides.svg}
          className={classNames(defaultcss.all, sty.svg)}
          role={"img"}
        />
      </div>

      <div className={classNames(defaultcss.all, sty.freeBox__d2Sh7)}>
        <ButtonCircleDelete
          data-plasmic-name={"buttonCircleDelete"}
          data-plasmic-override={overrides.buttonCircleDelete}
          className={classNames("__wab_instance", sty.buttonCircleDelete)}
          size={"_24Px" as const}
        />
      </div>
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "svg", "buttonCircleDelete"],
  svg: ["svg"],
  buttonCircleDelete: ["buttonCircleDelete"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  svg: "svg";
  buttonCircleDelete: typeof ButtonCircleDelete;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTableBillingRecord__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTableBillingRecord__VariantsArgs;
    args?: PlasmicTableBillingRecord__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTableBillingRecord__Fetches;
  } & Omit<PlasmicTableBillingRecord__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTableBillingRecord__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTableBillingRecord__ArgProps,
      internalVariantPropNames: PlasmicTableBillingRecord__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTableBillingRecord__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTableBillingRecord";
  } else {
    func.displayName = `PlasmicTableBillingRecord.${nodeName}`;
  }
  return func;
}

export const PlasmicTableBillingRecord = Object.assign(
  // Top-level PlasmicTableBillingRecord renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    buttonCircleDelete: makeNodeComponent("buttonCircleDelete"),

    // Metadata about props expected for PlasmicTableBillingRecord
    internalVariantProps: PlasmicTableBillingRecord__VariantProps,
    internalArgProps: PlasmicTableBillingRecord__ArgProps
  }
);

export default PlasmicTableBillingRecord;
/* prettier-ignore-end */
