// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: rEWzrkh7nZnDtT1
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ElementRadioPrimary from "../../ElementRadioPrimary"; // plasmic-import: LCJ0Mh3XlqeJy94/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicRadioTextInputPrimary.module.css"; // plasmic-import: rEWzrkh7nZnDtT1/css

export type PlasmicRadioTextInputPrimary__VariantMembers = {
  size: "_12Px" | "_14Px" | "_16Px";
};

export type PlasmicRadioTextInputPrimary__VariantsArgs = {
  size?: SingleChoiceArg<"_12Px" | "_14Px" | "_16Px">;
};

type VariantPropType = keyof PlasmicRadioTextInputPrimary__VariantsArgs;
export const PlasmicRadioTextInputPrimary__VariantProps =
  new Array<VariantPropType>("size");

export type PlasmicRadioTextInputPrimary__ArgsType = {
  itemText?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRadioTextInputPrimary__ArgsType;
export const PlasmicRadioTextInputPrimary__ArgProps = new Array<ArgPropType>(
  "itemText"
);

export type PlasmicRadioTextInputPrimary__OverridesType = {
  root?: p.Flex<"div">;
  parent?: p.Flex<"div">;
  elementRadioPrimary?: p.Flex<typeof ElementRadioPrimary>;
};

export interface DefaultRadioTextInputPrimaryProps {
  itemText?: React.ReactNode;
  size?: SingleChoiceArg<"_12Px" | "_14Px" | "_16Px">;
  className?: string;
}

function PlasmicRadioTextInputPrimary__RenderFunc(props: {
  variants: PlasmicRadioTextInputPrimary__VariantsArgs;
  args: PlasmicRadioTextInputPrimary__ArgsType;
  overrides: PlasmicRadioTextInputPrimary__OverridesType;
  dataFetches?: PlasmicRadioTextInputPrimary__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"parent"}
        data-plasmic-override={overrides.parent}
        hasGap={true}
        className={classNames(defaultcss.all, sty.parent, {
          [sty.parent__size__12Px]: hasVariant(variants, "size", "_12Px")
        })}
      >
        <ElementRadioPrimary
          data-plasmic-name={"elementRadioPrimary"}
          data-plasmic-override={overrides.elementRadioPrimary}
          className={classNames("__wab_instance", sty.elementRadioPrimary, {
            [sty.elementRadioPrimary__size__12Px]: hasVariant(
              variants,
              "size",
              "_12Px"
            ),
            [sty.elementRadioPrimary__size__16Px]: hasVariant(
              variants,
              "size",
              "_16Px"
            )
          })}
          size={
            hasVariant(variants, "size", "_12Px")
              ? ("_12Px" as const)
              : ("_14Px" as const)
          }
        />

        {p.renderPlasmicSlot({
          defaultContents: "Item element",
          value: args.itemText,
          className: classNames(sty.slotItemText, {
            [sty.slotItemText__size__12Px]: hasVariant(
              variants,
              "size",
              "_12Px"
            ),
            [sty.slotItemText__size__14Px]: hasVariant(
              variants,
              "size",
              "_14Px"
            ),
            [sty.slotItemText__size__16Px]: hasVariant(
              variants,
              "size",
              "_16Px"
            )
          })
        })}
      </p.Stack>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "parent", "elementRadioPrimary"],
  parent: ["parent", "elementRadioPrimary"],
  elementRadioPrimary: ["elementRadioPrimary"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  parent: "div";
  elementRadioPrimary: typeof ElementRadioPrimary;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRadioTextInputPrimary__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRadioTextInputPrimary__VariantsArgs;
    args?: PlasmicRadioTextInputPrimary__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRadioTextInputPrimary__Fetches;
  } & Omit<PlasmicRadioTextInputPrimary__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRadioTextInputPrimary__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRadioTextInputPrimary__ArgProps,
      internalVariantPropNames: PlasmicRadioTextInputPrimary__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRadioTextInputPrimary__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRadioTextInputPrimary";
  } else {
    func.displayName = `PlasmicRadioTextInputPrimary.${nodeName}`;
  }
  return func;
}

export const PlasmicRadioTextInputPrimary = Object.assign(
  // Top-level PlasmicRadioTextInputPrimary renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    parent: makeNodeComponent("parent"),
    elementRadioPrimary: makeNodeComponent("elementRadioPrimary"),

    // Metadata about props expected for PlasmicRadioTextInputPrimary
    internalVariantProps: PlasmicRadioTextInputPrimary__VariantProps,
    internalArgProps: PlasmicRadioTextInputPrimary__ArgProps
  }
);

export default PlasmicRadioTextInputPrimary;
/* prettier-ignore-end */
