// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4BLiU6oPcZdXDvseuPTeUa
// Component: qjiIFPDdbtvkZl9
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_copy_of_market_v_2.module.css"; // plasmic-import: 4BLiU6oPcZdXDvseuPTeUa/projectcss
import * as sty from "./PlasmicTagMemberB.module.css"; // plasmic-import: qjiIFPDdbtvkZl9/css

export type PlasmicTagMemberB__VariantMembers = {
  inset: "inset";
};

export type PlasmicTagMemberB__VariantsArgs = {
  inset?: SingleBooleanChoiceArg<"inset">;
};

type VariantPropType = keyof PlasmicTagMemberB__VariantsArgs;
export const PlasmicTagMemberB__VariantProps = new Array<VariantPropType>(
  "inset"
);

export type PlasmicTagMemberB__ArgsType = {};
type ArgPropType = keyof PlasmicTagMemberB__ArgsType;
export const PlasmicTagMemberB__ArgProps = new Array<ArgPropType>();

export type PlasmicTagMemberB__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultTagMemberBProps {
  inset?: SingleBooleanChoiceArg<"inset">;
  className?: string;
}

function PlasmicTagMemberB__RenderFunc(props: {
  variants: PlasmicTagMemberB__VariantsArgs;
  args: PlasmicTagMemberB__ArgsType;
  overrides: PlasmicTagMemberB__OverridesType;
  dataFetches?: PlasmicTagMemberB__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__inset]: hasVariant(variants, "inset", "inset")
      })}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(
          defaultcss.all,
          defaultcss.__wab_text,
          sty.freeBox,
          { [sty.freeBox__inset]: hasVariant(variants, "inset", "inset") }
        )}
      >
        {"startup"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTagMemberB__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTagMemberB__VariantsArgs;
    args?: PlasmicTagMemberB__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicTagMemberB__Fetches;
  } & Omit<PlasmicTagMemberB__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTagMemberB__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTagMemberB__ArgProps,
      internalVariantPropNames: PlasmicTagMemberB__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicTagMemberB__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTagMemberB";
  } else {
    func.displayName = `PlasmicTagMemberB.${nodeName}`;
  }
  return func;
}

export const PlasmicTagMemberB = Object.assign(
  // Top-level PlasmicTagMemberB renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicTagMemberB
    internalVariantProps: PlasmicTagMemberB__VariantProps,
    internalArgProps: PlasmicTagMemberB__ArgProps
  }
);

export default PlasmicTagMemberB;
/* prettier-ignore-end */
